platform independent?

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -133,8 +133,13 @@ jobs:
         run: cabal check
 
       - name: Build documentation
+        id: haddock
         env:
           cmd: cabal haddock all --disable-documentation
         run: |
           ${{ env.cmd }}
-          if (${{ env.cmd }} | grep Missing); then exit 1; fi
+          echo "missing=$(${{ env.cmd }} | grep Missing -m 1)" >> $GITHUB_OUTPUT
+
+      - name: Check documentation coverage
+        if: ${{ steps.haddock.outputs.missing }}
+        run: exit 1
